title: Machine Learning 2022-I
description: Universidad Nacional de Colombia, Bogotá
sitename: Machine Learning
baseurl: '/ml-2022-1'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
